export class AddressJson {
  addrss_id: number = null;
  app_id: number = null;
  per_id: number = null;
  strt_nm: string = null;
  ext_num: string = null;
  int_num: string = null;
  zip_cod: string = null;
  subt_nm: string = null;
  towt_nm: string = null;
  sta_cod: string = null;
  sta_spec: string = null;
  cntry_cod: string = null;
  cntry_spe: string = null;
  hom_phon: string = null;
  lab_phon: string = null;
  extt_num: string = null;
  cel_phon: string = null;
  per_mail_nm: string = null;
  lab_mail_nm: string = null;
  mncplty_nm: string = null;
  rec_crt_ts: string = null;
  rec_crt_usr_id: string = null;
  rec_updt_ts: string = null;
  rec_updt_usr_id: string = null;
}
