import {AgentJson} from './agentJson/agentJson';
import {FormatJson} from './formatJson/formatJson';
import {QuesList} from './questionaryJson/quesList';
import {QuesAns} from './questionaryJson/quesAns';
import {AccountJson} from './accountJson';
import {ForeignCountryTaxJson} from './foreignCountryTaxJson';
import {ExtraDataJson} from './extraDataJson';
import {DocumentJson} from './documentJson';
import {PersonJson} from './personJson';
import {InsuredConditionJson} from './insuredConditionJson';
import {ApplicationExtensionJson} from './applicationExtensionJson';
import {ShareHolderApp} from './shareHolderApp';

export interface ApplicationJson {
  app_id: number;
  agents: AgentJson[];
  Format: FormatJson[];
  QuesList: QuesList[];
  QuesAns: QuesAns[];
  insured: PersonJson;
  insurer: PersonJson;
  shareHolders: ShareHolderApp[];
  accounts: AccountJson[];
  foreignCountryTaxes: ForeignCountryTaxJson[];
  extraData: ExtraDataJson[];
  applicationExtension: ApplicationExtensionJson;
  documents: DocumentJson[];
  insuredCondition: InsuredConditionJson;
  app_bsns_ln_id: string;
  app_prdct_id: string;
  app_typ_cd: boolean;
  app_bus_typ_cd: string;
  app_dcn_num: string;
  app_phys_fol_num: string;
  app_st_pa: number;
  app_stts_cd: string;
  app_ctrl_num: string;
  app_pol_num: string;
  app_input_dt: string;
  app_crt_dt: string;
  app_rcpt_dt: string;
  app_eff_dt: string;
  app_guard_box_ind: boolean;
  app_own_tp_ind: boolean;
  app_own_card_num: string;
  app_own_card_typ_cd: string;
  app_own_card_typ_cd_id: boolean;
  app_own_card_subtyp_cd_id: boolean;
  app_own_card_emsr: string;
  app_own_card_rvw_ind: boolean;
  app_own_fin_prvd_ind: boolean;
  app_own_age_in_yr: number;
  app_own_frgn_cntrc_rsn_txt: string;
  app_own_ptrmnl_bond_ind: boolean;
  app_own_py_frgn_tax_ind: boolean;
  app_own_pltcl_dclr_ind: boolean;
  app_own_frng_ind: boolean;
  app_own_frng_spec: string;
  app_own_shre_ind: boolean;
  app_own_thrd_prty_ind: boolean;
  app_own_pymnt_rdrc_ind: boolean;
  app_own_rcv_email_ind: boolean;
  app_own_oth_lif_ins_ind: boolean;
  app_own_oth_lif_ins_nm: string;
  app_own_oth_lif_indamnt: number;
  app_ruse_priv_0_ind: boolean;
  app_ruse_priv_1_ind: boolean;
  app_ruse_priv_2_ind: boolean;
  chnl_cd: boolean;
  agnt_cd: string;
  vnd_ctrl_num: string;
  vnd_full_nm: string;
  vnd_wrk_plc_nm: string;
  rec_crt_ts: string;
  rec_crt_usr_id: string;
  rec_updt_ts: string;
  rec_updt_usr_id: string;
  promo_ofc_cmnt_txt: string;
  intactn_msg_txt: string;
  bpm_prcss_instnc_id: string;
  aura_fnl_rspns_cd: string;
  aura_fnl_rspns_txt: string;
  app_rjct_txt: string;
  app_add_commts: string;
}
