export class DocumentJson {
  doc_id: number = null;
  app_id: number = null;
  doc_party_rfr_id: number = null;
  doc_md_txt: string = null;
  doc_mgmt_file_id: string = null;
  doc_typ_cd: string = null;
  doc_sbtyp_cd: string = null;
  doc_class_cd: string = null;
  doc_cmnt_txt: string = null;
  rec_crt_ts: string = null;
  rec_crt_usr_id: string = null;
  rec_updt_ts: string = null;
  rec_updt_usr_id: string = null;
  doc_rqr_dscr: string = null;
  doc_short_dscr: string = null;
  doc_lng_dscr: string = null;
  doc_dcl_rsn_txt: string = null;
  doc_stts: boolean = null;
}
