import {BeneciciaryJson} from '../beneciciaryJson';

export class Cvr {
  cvr_cd: string = null;
  pln_cd: string = null;
  ins_id: number = null;
  app_id: number = null;
  cvr_nm: string = null;
  cvr_dt: string = null;
  beneciciary: BeneciciaryJson[] = [];
  cvr_face_amt: number = null;
  cvr_cmplmntry_ind: boolean = null;
  job_rul_fctr_cd: string = null;
  job_xtra_prem_amt: number = null;
  lqdtn_typ_cd: boolean = null;
  med_xtra_prem_amt: number = null;
  med_rul_fctr_num: string = null;
  prem_amt: number = null;
  trm_cd: string = null;
  input_face_val_amt_typ_cd: number = null;
  opt_face_val_cd: string = null;
  opt_face_val_amt: number = null;
  ins_cvr_role_cd: string = null;
  cvr_bene_typ_nm: string = null;
  cvr_stts_cd: boolean = null;
  cvr_edit_ind: boolean = null;
  cvr_scrn_cd: string = null;
  rec_crt_ts: string = null;
  rec_crt_usr_id: string = null;
  rec_updt_ts: string = null;
  rec_updt_usr_id: string = null;
  init_cvr_face_amt: number = null;
  init_prem_amt: number = null;
}
