export class BankAccount {
  bnk_acct_id?: number = null;
  clct_id?: number = null;
  app_id?: number = null;
  pymnt_prrty?: string = null;
  bnk_acct_num?: string = null;
  bnk_acct_tkn_num?: string = null;
  mbr_area_nm?: string = null;
  std_bnk_cd?: string = null;
  bnk_cd?: string = null;
  clct_prps_day_1_cd?: string = null;
  clct_prps_day_2_cd?: string = null;
  clct_prps_day_3_cd?: string = null;
  clct_prps_day_4_cd?: string = null;
  rec_crt_ts?: string = null;
  rec_crt_usr_id?: string = null;
  rec_updt_ts?: string = null;
  rec_updt_usr_id?: string = null;
  bnk_nm?: string = null;
  bnk_bin_id?: string = null;
}
